name: Clippings
favicon: null
layout_spectrum: 0.4814400775358081
typography_spectrum: 0.1252954937517643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13867895142175257
  lightness: 0.6376206134445965
  saturation: 0.8448486712295562
  rhythmicContrast: 0.4406589788850397
purpose: []
